# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addDebugMessageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generate.setGeometry(QtCore.QRect(510, 110, 75, 23))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.groupBox_DB = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_DB.setGeometry(QtCore.QRect(10, 100, 481, 91))
        self.groupBox_DB.setObjectName("groupBox_DB")
        self.lineEdit_DB = QtWidgets.QLineEdit(self.groupBox_DB)
        self.lineEdit_DB.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.lineEdit_DB.setObjectName("lineEdit_DB")
        self.toolButton_DB = QtWidgets.QToolButton(self.groupBox_DB)
        self.toolButton_DB.setGeometry(QtCore.QRect(450, 20, 25, 19))
        self.toolButton_DB.setObjectName("toolButton_DB")
        self.label_3 = QtWidgets.QLabel(self.groupBox_DB)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_excel = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_excel.setGeometry(QtCore.QRect(10, 200, 481, 91))
        self.groupBox_excel.setObjectName("groupBox_excel")
        self.lineEdit_excel = QtWidgets.QLineEdit(self.groupBox_excel)
        self.lineEdit_excel.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.lineEdit_excel.setObjectName("lineEdit_excel")
        self.toolButton_excel = QtWidgets.QToolButton(self.groupBox_excel)
        self.toolButton_excel.setGeometry(QtCore.QRect(450, 20, 25, 19))
        self.toolButton_excel.setObjectName("toolButton_excel")
        self.label_2 = QtWidgets.QLabel(self.groupBox_excel)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_generate.setText(_translate("MainWindow", "generate"))
        self.groupBox_DB.setTitle(_translate("MainWindow", "DBC"))
        self.toolButton_DB.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "拖入选择文件"))
        self.groupBox_excel.setTitle(_translate("MainWindow", "Excel"))
        self.toolButton_excel.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "拖入选择文件"))
